name: Deploy shield to YC
run-name: ${{ github.actor }} start deploing shield to YC
on: [workflow_dispatch]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        working-directory: backend-example
        env:
          CR_REGISTRY: crpgvh3nlf7rueqfkpp9
          CR_REPOSITORY: backend-example
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: backend-example
          folder-id: b1gnqp117e39mo1e404f
          revision-service-account-id: ajed2c0sgtct380i7cqo
          revision-cores: 1
          revision-memory: 512Mb
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-image-url: cr.yandex/crpgvh3nlf7rueqfkpp9/backend-example:${{ github.sha }}
          revision-execution-timeout: 10
          revision-secrets: DATABASE_URL=e6qou55m288s767ej1ca/e6q1lne50v7m5bvudbih/DATABASE_URL
